[project]
name = "@kit-data-manager/react-search-component"
version = "0.4.1"
description = "All-in-one component for rendering an elastic search UI for searching anything. Built-in support for visualizing related items in a graph and resolving unique identifiers."
license = "Apache-2.0"
repository = "https://github.com/kit-data-manager/react-search-component"
homepage = "https://kit-data-manager.github.io/react-search-component/"
documentation = "https://kit-data-manager.github.io/react-search-component/"
keywords = [
  "react",
  "reactjs",
  "component",
  "elastic",
  "search",
  "elasticsearch",
  "kit-data-manager",
  "typescript",
  "storybook",
  "tailwindcss",
  "fair",
  "fairdata",
  "fairdo",
  "fairdigitalobject",
  "kit",
  "data",
  "manager"
]

[[project.people]]
given-names = "Christopher"
family-names = "Raquet"
email = "christopher.raquet@kit.edu"
orcid = "https://orcid.org/0009-0003-2196-9187"
affiliation = "Karlsruhe Institute of Technology (KIT)"
author = true      # is a full author of the project (i.e. appears in citations)
maintainer = true  # currently maintains the project (i.e. is a contact person)

[config]
verbose = true     # show detailed information about what somesy is doing